<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FMS.DataCollector</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\FMS.SharedKernel.csproj" />
    <ProjectReference Include="..\..\MessageBus\FMS.MessageBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.6.959" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
  </ItemGroup>

</Project>
